export const EVENT_ERRORS = {
    PAY_COMMISSION: 'Please select Pay Commission',
    ORDER_NO: 'Please Enter Order Number',
    ORDER_DATE: 'Please select Enter Order Date',
    PAY_BAND: 'Please Select Pay Band',
    GRADE_PAY: 'Please Select Grade Pay',
    GRADE: 'Please Select Grade Pay',
    PAY_LEVEL: 'Please Select Pay Level',
    PAY_SCALE: 'Please Select Pay Scale',
    CELL_ID: 'Please Select Cell Id',
    INCREMENT_AMT: 'Please Select Option',
    OPTION_AVAILED: 'Please Select Option availed or Not',
    OPTION_TYPE: 'Please Select Type',
    EVENT_SUB_TYPE: 'Please Select Event Sub Type',
    BENEFIT_EFFECTIVE_DATE: 'Please select Benefit Effective Date',
    DATE_OF_NEXT_INCREMENT: 'Please Select Date of Next Increment',
    EVENT_ORDER_DATE: 'Please Select Event Order Date',
    CLASS: 'Please Select Class',
    DESIGNATION: 'Please Select Designation',
    PAY_BAND_VALUE: 'Please Select Pay Band Value',
    PAY_BAND_MIN_MAX: 'Please Enter between selected pay band',
    BASIC_PAY: 'Please Enter Basic Pay',
    PERSONAL_PAY: 'Please Enter Personal Pay',
    BASIC_PAY_MIN: 'Please enter basic pay greater than ',
    BASIC_PAY_MAX: 'Please enter basic pay lesser than ',
    BASIC_PAY_MINPAY: 'Please enter basic pay greater than or equal to ',
    BASIC_PAY_MAXPAY: 'Please enter basic pay lesser than or equal to ',
    EVENT_ORDER_NUMBER: 'Please Select Event Order Number',
    DATE_OF_JOINING: 'Please Select Date of Joining',
    EVENT_EFFECTIVE_DATE: 'Please enter Event Effective Date',
    OFFICE_NAME: 'Please Enter Office Name',
    OPTION_DATE: 'Please Select Option date',
    SCALE: 'Please Select Scale',
    REMARKS: 'Please Enter Remarks',
    SR_SENIORITY_NO: 'Please enter Senior Employee Seniority No.',
    JR_SENIORITY_NO: 'Please enter Junior Employee Seniority No.',
    // Promotion Forgo
    PROMOTION_FOR: 'Please Select Promotion Porgo For',
    PROMOTION_DATE: ' Please Select Promotion Date',
    PROMOTION_FORGO_DATE: 'Please Select Promotion Forgo Date',
    HIGHER_GRADE: 'Please Select Higher Grade',
    JOIN_PROMOTIONAL_POST: 'Please Select Join Promotional Post',
    JOINING_DATE: 'Please Select  Joining Date',
    EMP_NO_MAX: 'Employee number should be of 10 digits!',

    // REVISED_BASIC_PAY
    REVISED_BASIC_PAY: 'Please Select Revised Basic Pay',
    REVISED_BASIC_PAY_VALUE: 'Please Select Revised Basic Pay Value',

    // Tikypay
    TIKU_PAY_TYPE: 'Please Select Tiku Pay Type',
    ADHOC: 'Please Select Adhoc',
    FROM_DATE: 'Please Select From date',
    TO_DATE: 'Please Select To Date',
    ADHOC_CONTINIOUS_SERVICES: 'Please Select Adhoc Continious Services',
    GPSC_EXAM_PASSED: 'Please Select Gpsc Exam Passed',
    GPSC_EXAM_PASSED_DATE: 'Please Select Gpsc Exam Passed Date',
    EMP_NO: 'Please fill Employee Number',
    TYPE: 'Please Select Option',

    // Higher Pay Scale
    HIGHER_PAY_TYPE: 'Please Select Type',
    OPTION_EMP_TYPE: 'Please Select Employee Type',

    // Employee Creation
    SALUTATION: 'Please select Option',
    EMPLOYEE_NAME: 'Please Enter Employee Name',
    GENDER: 'Please select Gender',
    NATIONALITY: 'Please select Nationality',
    EMPLOYEE_MOBILENO: 'Please Enter Employee Mobile No.',
    EMPLOYEE_EMAIL: 'Please Enter Email ID',
    FATHERS_NAME: 'Please Enter Employee Father Name',
    MOTHER_NAME: 'Please Enter Employee Mother Name',
    MARITAL_STATUS: 'Please Select Employee Marital Status',
    CATEGORY: 'Please select Category',
    RELIGION: 'Please Enter Religion',
    CASTE: 'Please Enter Caste',
    PH_STATUS: 'Please select Divyang (PH) Status',
    PH_TYPE: 'Please select PH Type',
    IDENTIFICATION_MARK: 'Please Enter Identification Mark',
    HEIGHT: 'Please Enter Height',
    PAN_NO: 'Please Enter Permanent Account No.(PAN)',
    STATE: 'Please select State',
    DISTRICT: 'Please select District',
    TALUKA: 'Please select Taluka',
    CITY_VILLAGE: 'Please Enter City/ Village',
    PIN_CODE: 'Please Enter Pincode',
    OFFICE_DISTANCE: 'Please select Distance from Office',
    EMP_CATEGORY: 'Please select Employee Type',
    EMP_STATUS: 'Please select Type of Employement',
    EMP_TYPE: 'Please select Employee PayType',
    PARENT_ADMIN_DEPT: 'Please select Parent Administrative Department',
    HEAD_OF_DEPT: 'Please select Head of Department',
    EMP_CLASS: 'Please select Employee Class',
    DEPARTMENTAL_CATEGORY: 'Please select Departmental Category',
    STATION: 'Please Enter Station',
    DEPT_NAME: 'Please Enter Department Name',
    OFFICE_ADD: 'Please Enter Office Address',
    EMP_DESIGNATION_HIST: 'Please select Employee Designation',
    LAST_PAY_DRAWN: 'Please Enter Last Pay Drawn',
    IS_SERVICE_CONTINUE: 'Please select Option',
    ORDER_NO_DATE: 'Please Enter Order No & Date',

    // Error Messages for Suspension
    REASON_FOR_SUSPENSION: 'Please select Reason for Suspension',
    SUSPENSION_START_DATE: 'Please select Suspension Start Date',
    SUSPENSION_END_DATE: 'Please select Suspension End Date',
    SUSPENSION_CLOSURE_DATE: 'Please select Suspension Closure Date',
    DESCRIPTION: 'Please fill Description',
    CLOSURE: 'Please select Closure',
    TYPE_OF_PUNISHMENT: 'Please fill Type of Punishment',
    SUSPENSION_EFFECTIVE_DATE: 'Please select Suspension Effective Date',
    SUSPENSION_EVENT_DATE: 'Please select Suspension Event Date',
    SUSPENSION_ORDER_NO: 'Please fill Supension Order Number',
    SUSPENSION_ORDER_DATE: 'Please select Suspension Order Date',

    // Error Messages for Selection Grade CAS
    CAS_TYPE: 'Please select Career Advancement Scheme Type',
    UNIVERSITY_APPROVED_LECTURER: 'Please fill University Approved Lecturer',
    ORIENTATION_COURSE: 'Please select Orientation Course Attended',
    ORIENTATION_DATE: 'Please select Orientation Date',
    REFRESHER_COURSE: 'Please select Refresher Course Attended',
    REFRESHER_DATE: 'Please select Refresher Course Date',

    // STEPPING UP ERROR MESSAGES
    JUNIOR_EMP_NO: 'Please Enter Employee Number',
    EVENT_DATE: 'Please Select Event Order Date',
    EVENT_ORD_NUMBER: 'Please Enter Event Order Number',

    // EOL ERROR MESSAGES
    LEAVE_START: 'Please Select Leave Start Date',
    LEAVE_END: 'Please Select Leave End Date',
    SUB_TYPE: 'Please Select Leave End Date',

    CARDEX_NO: 'Please Select Cardex Number',
    DDO_NO: 'Please Select DDO Number',
    FORENOON_AFTERNOON: 'Please Select Forenoon/ Afternoon',
    DECLINED_PROMOTION: 'Please Select Option',

    DESIGNATION_TXT: 'Please Enter Designation',
    MORE_BASIC_PAY: 'Basic Pay should be more than Actual Pay'
};

export const EVENT_APIS = {
    EMPLOYEE_DETAILS: 'pvu/get-regular-common-detail',
    DEEMED_EMPLOYEE_DETAILS: 'pvu/eligible/deemed/date',
    PAY_EVENTS: 'pvu/payfixation-events',
    GET: '301',
    CREATE: '101',
    UPDATE: '401',
    DESIGNATIONS: 'masters/designations/201',
    PAY_MASTERS: 'pvu/pay-masters',
    OPTION_CALCULATE_API: 'pvu/option/calculate/601',
    PAY_MASTERS_COMMISSION: 'pvu/pay-masters-commission',
    ATTACHMENT_PREFIX: {
        Promotion: 'pvu/promotion',
        Deemed_Date: 'pvu/deemed-date',
        Reversion: 'pvu/pvuemployereversion',
        Promotion_Forgo: 'pvu/employepaydetail/seven/basic/pay',
        Senior_Scale: 'pvu/senior-scale',
        Change_of_Scale: 'pvu/csevent'
    },
    EMPLOYEE_JOINING_DETAILS: 'pvu/pvuemployereversion/paylevel/301',
    CAL_SEVEN_BASIC: {
        Promotion: 'pvu/seven/basic/pay',
        Deemed_Date: 'pvu/seven/basic/pay',
        Reversion: 'pvu/employepaydetail/seven/basic/cell',
        Promotion_Forgo: 'pvu/employepaydetail/seven/basic/pay',
        Senior_Scale: 'pvu/seven/basic/payPVU',
        Change_of_Scale: 'pvu/seven/basic/payPVU'
    },
    CAL_SIX_BASIC: {
        Promotion: 'pvu/six/basic/pay',
        Deemed_Date: 'pvu/six/basic/pay',
        Reversion: 'pvu/employepaydetail/seven/basic/pay',
        Senior_Scale: 'pvu/six/basic/pay',
        Change_of_Scale: 'pvu/six/basic/pay'
    },
    CHECK_FOR_ELIGIBILITY: 'pvu/check-employee-eligible',
    PROMOTION_ELIGIBILITY: 'pvu/promotion/validation',
    LIST: {
        GET_LOOKUP_DATA: 'pvu/get-all-lookup',
        LIST_DATA: 'pvu/common-details-pf',
        WORKFLOW_STATUS: 'common/workflow/getWfStatus/201',
        DELETE: 501
    },
    CRUD: {
        Promotion: 'pvu/promotion/',
        Senior_Scale: 'pvu/senior-scale/',
        Change_of_Scale: 'pvu/csevent/',
        Reversion: 'pvu/pvuemployereversion/',
        Promotion_Forgo: 'pvu/employe-forgo-event/',
        Deemed_Date: 'pvu/deemed-date/',
    },
    LOOK_UP: {
        Promotion: 'pvu/promotion/get-all-lookup',
        Senior_Scale: 'pvu/senior-scale/get-all-lookup',
        Change_of_Scale: 'pvu/csevent/pvu/getAllLookup',
        // Reversion: 'pvu/pvuemployereversion/601',
        Reversion: 'pvu/pvuemployereversion/getAvailableClasses/201',
        Promotion_Forgo: 'pvu/employe-forgo-event/pvu/getAllLookup',
        Deemed_Date: 'pvu/deemed-date/get-all-lookup',
    },
    PRINT_ORDER: {
        Promotion: 'pvu/promotion/generate-printendorsement/101',
        Senior_Scale: 'pvu/senior-scale/payfixation/generate-printendorsement/101',
        Change_of_Scale: 'pvu/csevent/payfixation/generate-printendorsement/101',
        Reversion: 'pvu/pvuemployereversion/generate-printendorsement/101',
        Deemed_Date: 'pvu/deemed-date/generate-printendorsement/101',
        Promotion_Forgo: '',
    },
    PRINT_COMPARISON_STATEMENT: 'pvu/deemed-date/generate-comparision-report/101',
    PAY_COMM: 'pvu/paycommision'
};
