export const APIConst = {
    LC_OPENING_REQUEST: {
        GET_TREASURY_OFFICE_DETAILS: 'loc/accopenreq/treasuryDetails/201',
        GET_CIRCLE_NAME_DETAILS: 'loc/accopenreq/circleDetails/201',
        GET_BANK_DETAILS: 'loc/accopenreq/getAllBankDetails/201',
        GET_EDIT_ACCOUNT_DETAILS: 'loc/accopenreq/accountOpenReqDtl/301',
        GET_AG_EDIT_ACCOUNT_DETAILS: 'loc/accopenreq/getAgDetail/201',
        GET_BANK_EDIT_DETAILS: 'loc/accopenreq/getBankDetail/201',
        GET_DIVISION_EDIT_DETAILS: 'loc/accopenreq/getDivisionDetail/201',
        GET_MAJOR_HEAD_LIST: 'loc/accopenreq/getMajorHead/201',
        GET_SUB_MAJOR_HEAD_LIST: 'loc/accopenreq/getSubMajorHead/201',
        GET_MINOR_HEAD_LIST: 'loc/accopenreq/getMinorHead/201',
        GET_SUB_HEAD_LIST: 'loc/accopenreq/getSubHead/201',
        GET_DETAIL_HEAD_LIST: 'loc/accopenreq/getDetailHead/201',
        GET_OPENING_REQUEST_AG_VIEW: 'loc/accopenreq/getOpenReqAgView/201',
        GET_OPENING_REQUEST_BANK_VIEW: 'loc/accopenreq/getOpenReqBankView/201',
        GET_OPENING_REQUEST_DIVISION_VIEW: 'loc/accopenreq/getOpenReqDiviView/201',
        GET_OPENING_REQUEST_VIEW: 'loc/accopenreq/getOpenReqView/201',
        SAVE_BANK_DETAILS: 'loc/accopenreq/postBankDetail/101',
        SUBMIT_WF_DETAILS: 'loc/accopenreq/submitOpenReq/201',
        DROP_DOWN: 'loc/accopenreq/getSearchParam/201',
        GET_SEARCHED_LIST: 'loc/accopenreq/getOpenListing/201',
        GET_HEADER_DATA: 'loc/accopenreq/accountOpenReqHdr/301',
        // DELETE_ROW: 'loc/accopenreq/accountOpenReqSd/501',
        DELETE_ROW: 'loc/accopenreq/accountOpenReqHdr/501',
        DIVISION_TAB_SAVE: 'loc/accopenreq/postDivisionDetail/101',
        VALIDATION_AG: 'loc/accopenreq/validateAgOffDtl/201',
        SUBMIT_ACTION_DETAILS: 'loc/accopenreq/getAgWfDetail/201',
        SAVE_DIVISION_DETAILS: 'loc/accopenreq/postDivisionDetail/201',
        OPENING_REQUEST_SUBMIT: 'loc/accopenreq/submitOpenReq/201',
        OPEN_REQUEST_SAVE_AND_PROCESS: 'loc/accopenreq/accountOpenReqHdr/101',
        AG_OFFICE_SAVE_AND_PROCESS: 'loc/accopenreq/postAgDetail/101',
        SUBMIT_CONDITIONAL_API: 'loc/accopenreq/2001',
        GET_HEADER_EXISTS_DETAILS: 'loc/accopenreq/getDivisionValidation/201',
        GET_CIRCLE_DETAILS: 'loc/accopenreq/circleDetails/departmentId/201',
        GET_OPEN_REQ_PRINT_AUTH_LETTER: 'loc/accopenreq/getprintauthletterpdf/201'


    },
    CHECKBOOK_ACTIVE_INACTIVE: {
        CHECK_BOOK_LISTING: 'loc/chequeBook/getListing/201',
        CHECK_BOOK_lISTING_SEARCH_PARAMS: 'loc/chequeBook/getSearchParam/201',
        GET_CHEQUEBOOK_DATA: 'loc/chequeBook/getChequeBookData/201',
        GET_CHEQUEBOOK_LIST_DATA: 'loc/chequeBook/getChequeBookList/201',
        GET_CHEQUEBOOK_SAVE_DRAFT: 'loc/chequeBook/saveDraft/101',
        GET_CHEQUEBOOK_SEARCH_PARAM: 'loc/chequeBook/getSearchParam/201',
        GET_CHEQUEBOOK_SUBMIT_DETAILS: 'loc/chequeBook/submit/101',
        GET_CHEQUEBOOK_GETHEARDER: 'loc/chequeBook/getHeaderInfo/201',
        GET_EDIT_VIEW_DATA: 'loc/chequeBook/getEditView/201',
        DELETE_CHECKBOOK_DATA: 'loc/chequeBook/delete/501',

    },

    LC_CLOSEREQUEST: {
        GET_LC_OPENREQ_DATA: 'loc/accclosereq/accountCloseReqDtl/101',
        SAVE_AS_DRAFT: 'loc/accclosereq/accountCloseReqHdr/101',
        SUBMIT_ACTION_DETAILS: 'loc/accclosereq/getEditView/201',
        SUBMIT_WF_DETAILS: 'loc/accclosereq/submitCloseReq/201',
        DROP_DOWN: 'loc/accclosereq/getSearchParam/201',
        GET_SEARCHED_LIST: 'loc/accclosereq/getCloseListing/201',
        VIEW_HISTORY: 'loc/accclosereq/getclosingReqView/201',
        DELETE_ROW: 'loc/accclosereq/delete/501',
    },
    LC_DISTRIBUTION: {
        GET_LC_SEARCH_PARAMS: 'loc/Distribution/getSearchParam/201',//get all districts
        GET_DISTRIBUTION_LISTING: 'loc/Distribution/getListing/201',
        DISTRIBUTION_SUBMIT: 'loc/Distribution/submit/101',
        GET_EDIT_VIEW_DETAILS: 'loc/Distribution/getEditView/201',
        GET_DISTRIBUTION_PRINT_PDF: 'loc/Distribution/getprintformbpdf/201',
        GET_DISTRIBUTION_PRINT_FORM_A_PDF:'loc/Distribution/getprintformApdf/201'
    },
    LC_ADVICEPREPARATION: {
        GET_LC_CHEQUETYPE_DROPDOWN: 'loc/adviceprep/getadvicedtlchequetype/201',
        GET_POSTING_DETAILS_MAPDATA: 'loc/adviceprep/getpostingdtlmapepaymt/201',
        GET_POSTING_DETAILS_LC_SEARCH: 'loc/adviceprep/getpostingdtlssearchLC/201',
        // GET_POSTING_DETAILS_TABLE_DATA:'loc/adviceprep/getpostingdtls/201',
        GET_POSTING_DETAILS_EDIT_VIEW_DATA: 'loc/adviceprep/getpostingdtleditview/201',
        GET_DEMAND_LIST: 'loc/adviceprep/getdemandlist',
        GET_POSTING_DETAILS_ADVICE_TYPE: 'loc/adviceprep/getpostingdtladvicetype/201',
        GET_MAJOR_HEAD_LIST: 'loc/adviceprep/getmajorheadlist',
        GET_SUB_MAJOR_HEAD_LIST: 'loc/adviceprep/getsubmajorheadlist',
        GET_MINOR_HEAD_LIST: 'loc/adviceprep/getminorheadlist',
        GET_SUB_HEAD_LIST: 'loc/adviceprep/getsubheadlist',
        GET_DETAIL_HEAD_LIST: 'loc/adviceprep/getdetailheadlist',
        GET_OBJECT_CLASS_LIST: 'loc/adviceprep/getobjectclasslist',
        GET_ITEM_LIST: 'loc/adviceprep/getitemlist',
        GET_BUDGET_ESTIMATE_TYPE_LIST: 'loc/adviceprep/getbudgetestimate',
        GET_FUNDTYPE_LIST: 'loc/adviceprep/getfundtype',
        GET_CHARGE_VOTED_LIST: 'loc/adviceprep/getchargedvoted',
        GET_BUDGET_TYPE_LIST: 'loc/adviceprep/getbudgettype',
        GET_POSTING_DETAILS_TABLE_LIST: 'loc/adviceprep/postingdtlsadd',
        POSTING_DETAILS_SAVE_AND_PROCESS: 'loc/adviceprep/getpostingdtlsave/201',
        POSTING_DETAILS_MAP_UPDATE: 'loc/adviceprep/postingdtlupdtepaymt/201',
        POSTING_DETAILS_DELETE: 'loc/adviceprep/postingdtlsdelete',
        GET_ADVICE_DTL: 'loc/adviceprep/getAdviceDtlData/201',
        GET_ADVICEPREP_EDIT: 'loc/adviceprep/getadvicedtleditView/201',
        SAVE_LCPREP_DATA: 'loc/adviceprep/advicedtlsave/101',
        SUBMIT_WF_DETAILS: 'loc/adviceprep/submit/101',
        DROP_DOWN: 'loc/adviceprep/getSearchParam/201',
        INWARD_DROP_DOWN: 'loc/adviceprep/getInwardSrchParam/201',
        CARDEX_VERIFICATION_DROP_DOWN: 'loc/adviceprep/getCardexVerifySrchParam/201',
        ADVICE_VERIFICATION_DROP_DOWN: 'loc/adviceprep/getAdviceVerifySrchParam/201',
        ADVICE_AUTHORIZATION_DROP_DOWN: 'loc/adviceprep/getAdviceAuthSrchParam/201',
        DELETE_ROW: 'loc/adviceprep/delete/501',
        GET_SEARCHED_LIST: 'loc/adviceprep/getadviceprepListing/201',
        PAYMENTDETAILS_DROPDOWN: 'loc/adviceprep/getchequetypeSrchData/201',
        NON_EMPLOYEE_LIST: 'loc/adviceprep/getchequetypeListing/201',
        GET_EPAY_SAVE: 'loc/adviceprep/loccheqepaysave/101',
        GET_HEADER_DATA: 'loc/adviceprep/getHeaderInfo/201',
        GET_ADVICEPREP_CHEQUEBOOK_DATA: 'loc/adviceprep/getcheckbookdata/201',
        GET_ADVICEPREP_EPAY_EDIT: 'loc/adviceprep/getcheckpayeditview/201',
        DELETE_EPAY_ROW: 'loc/adviceprep/checkPayDelete/201',
        GET_DEDUCTION_SAVEDATA: 'loc/adviceprep/advicededuction/201',
        GET_DEDUCTION_DETAIL_EDIT_VIEW_DATA: 'loc/adviceprep/getadvicedededitview/201',
        GET_OPENING_AND_NEWBALANCE_AMOUNT: 'loc/adviceprep/getopeningnewbalance',
        GET_INWARD_LISTING: 'loc/adviceprep/getinwardadvicelisting/201',
        GET_CARDEX_VERIFICATION_LISTING: 'loc/adviceprep/getcardexverficationlisting/201',
        GET_ADVICE_VERIFICATION_LISTING: 'loc/adviceprep/getadviceverificationlisting/201',
        GET_ADVICE_AUTHORIZATION_LISTING: 'loc/adviceprep/getadviceauthorizationlisting/201',
        TOKEN_GENERATION_API: 'loc/adviceprep/generatetokenno/201',
        ON_RECEIVE_API: 'loc/adviceprep/onreceive/201',
        INWARD_MULTIPLE_USER: 'loc/adviceprep/getMultipleInward/201',
        CARDEX_VERIFY_MULTIPLE_USER: 'loc/adviceprep/getMultipleCardexVerify/201',
        GET_ADVICE_STATEMENT_PDF: 'loc/adviceprep/getadvicestatementpdf/201',
        GET_ADVICE_CHEQ_EPAYMENT_PRINT: 'loc/adviceprep/getprintadviceletterpdf/201',
        NOTIFICATION_DATA:'loc/adviceprep/sendNotification/201',
        IMAGE_DOWNLOAD: 'common/attachment/filenet/imagedownload/901',
        LC_USED_AMOUNT_API:'loc/adviceprep/searchLCAdvcAmnts/201'

    },



    LC_CHEQUE_CANCEL: {

        DROP_DOWN: 'loc/chequecancel/getSearchParam/201',
        GET_HEADER_DATA: 'loc/chequecancel/getHeaderInfo/201',
        DELETE_ROW: 'loc/chequecancel/delete/501',
        GET_CHEQUECANCEL_DATA: 'loc/chequecancel/searchchequedetail/201',
        SAVEDATA_CHEQUECANEL: 'loc/chequecancel/saveDraft/101',
        WFSUBMIT_CHEQUECANCE: 'loc/chequecancel/submit/101',
        EDITVIEW_CHEQUECANCEL: 'loc/chequecancel/getEditView/201',
        GET_CHEQUE_CANCEL_LISTING: 'loc/chequecancel/getchequecancellisting',
        GET_DIV_CHEQUE_CANCEL_LISTING: 'loc/chequecancel/getchequecanceldivlisting'

    },

    LC_CHEQUE_TO_CHEQUE_EFFECT: {
        DROP_DOWN: 'loc/chequetocheque/getSearchParam/201',
        GET_CHEQUE_CANCEL_LISTING: 'loc/chequetocheque/getchequetochequelisting',
        GET_HEADER_DATA: 'loc/chequetocheque/getHeaderInfo/201',
        DELETE_ROW: 'loc/chequetocheque/delete/501',
        SAVEDATA_CHEQUEEFFECT: 'loc/chequetocheque/saveDraft/101',
        WFSUBMIT_CHEQUECANCE: 'loc/chequetocheque/submit/101',
        EDITVIEW_CHEQUECANCEL: 'loc/chequetocheque/getEditView/201',
        GET_CHEQUEEFFECT_DATA: 'loc/chequetocheque/searchchequedetail/201',
        DELETE_EPAY_ROW: 'loc/chequetocheque/deleteCheque/501'
    }
    

}