export const EVENT_CONST_DATA = {
    HIGHER_PAY_SCALE: 'Higher_Pay_Scale',
    TIKU_PAY: 'Tiku_Pay',
    ASSURED_CARREER_PROGRESSION: 'Assured_Career_Progression',
    STEPPING_UP: 'Stepping_Up',
    SELECTION_GRADE: 'Selection_Grade',
    SHETTY_PAY: 'Shetty_Pay',
    CARREER_ADVANCEMENT_SCHEME: 'Career_Advancement_Scheme',
    SENIOR_SCALE_PVU: 'Senior_Scale_PVU',
    CHANGE_OF_SCALE_PVU: 'Change_of_Scale_PVU'
};
export const EVENT_ERRORS = {
    MANDATORY_FIELDS: 'Please fill mandatory fields!',
    ACP_NOT_ELIGIBLE: 'Employee is not eligible for ACP!',
    ACP_EVENT_NOT_INITIATED: 'Event can\'t be initiated as employee has undergone Promotion Forgo on personal grounds!',
    POST_CONSIGMENT_ERROR: 'Please enter post consignment number',
    STEPPING_JNR_ERROR: 'Please fetch junior details by pressing enter or tab button on junior employee number field!',
    EMPLOYEE_NOT_SEARCHED: 'Please fetch employee details by pressing enter or tab button on employee number field!',
    PAY_COMMISSION: 'Please select Pay Commission',
    ORDER_NO: 'Please Enter Order Number',
    ORDER_DATE: 'Please Enter Order Date',
    PAY_BAND: 'Please Select Pay Band',
    GRADE_PAY: 'Please Select Grade Pay',
    GRADE: 'Please Select Grade Pay',
    PAY_LEVEL: 'Please Select Pay Level',
    PAY_SCALE: 'Please Select Pay Scale',
    CELL_ID: 'Please Select Cell Id',
    INCREMENT_AMT: 'Please Select Option',
    OPTION_AVAILED: 'Please Select Option availed or Not',
    OPTION_DATE: 'Please Select Option date',
    OPTION_TYPE: 'Please Select Type',
    BENEFIT_EFFECTIVE_DATE: 'Please select Benefit Effective Date',
    DATE_OF_NEXT_INCREMENT: 'Please Select Date of Next Increment',
    EVENT_ORDER_DATE: 'Please Select Event Order Date',
    CLASS: 'Please Select Class',
    DESIGNATION: 'Please Select Designation',
    PAY_BAND_VALUE: 'Please Select Pay Band Value',
    PAY_BAND_MIN_MAX: 'Please Enter between selected pay band',
    BASIC_PAY: 'Please Select Basic Pay',
    EVENT_ORDER_NUMBER: 'Please Select Event Order Number',
    DATE_OF_JOINING: 'Please Select Date of Joining',
    EVENT_EFFECTIVE_DATE: 'Please Select Event Effective Date',
    OFFICE_NAME: 'Please Enter Office Name',
    SCALE: 'Please Select Scale',
    REMARKS: 'Please Enter Remarks',
    ERR_APPROVER_REMARKS: 'Please Enter Authorizer Remarks',
    ERR_AUDITOR_REMARKS: 'Please Enter Auditor Remarks',
    ERR_VERIFIER_REMARKS: 'Please Enter Verifier Remarks',
    ERR_APPROVERI_REMARKS: 'Please Enter Authorizer Class I Remarks',
    RETURN_REASON: 'Please Select Return Reason',
    YEAR: 'Please select Year',
    MONTH: 'Please select Month',
    // Promotion Forgo
    PROMOTION_FOR: 'Please Select Promotion Porgo For',
    PROMOTION_DATE: ' Please Select Promotion Date',
    PROMOTION_FORGO_DATE: 'Please Select Promotion Forgo Date',
    HIGHER_GRADE: 'Please Select Higher Grade',
    JOIN_PROMOTIONAL_POST: 'Please Select Join Promotional Post',
    JOINING_DATE: 'Please Select  Joining Date',
    DATE_MIN: 'Please enter date greater than ',
    DATE_MAX: 'Please enter date lesser than ',
    BASIC_PAY_MIN: 'Please enter basic pay greater than ',
    BASIC_PAY_MAX: 'Please enter basic pay lesser than ',
    EMP_NO_MAX: 'Employee number should be of 10 digits!',

    // REVISED_BASIC_PAY
    REVISED_BASIC_PAY: 'Please Select Revised Basic Pay',
    REVISED_BASIC_PAY_VALUE: 'Please Select Revised Basic Pay Value',

    // Tikypay
    TIKU_PAY_TYPE: 'Please Select Tiku Pay Type',
    ADHOC: 'Please Select Adhoc',
    FROM_DATE: 'Please Select From date',
    TO_DATE: 'Please Select To Date',
    ADHOC_CONTINIOUS_SERVICES: 'Please Select Adhoc Continious Services',
    GPSC_EXAM_PASSED: 'Please Select Gpsc Exam Passed',
    GPSC_EXAM_PASSED_DATE: 'Please Select Gpsc Exam Passed Date',
    EMP_NO: 'Please fill Employee Number',
    TYPE: 'Please Select Option',
    DOJ_REGULAR_SERVICE_DATE: 'Please Select Date of Joining in Regular Service',

    // Higher Pay Scale
    HIGHER_PAY_TYPE: 'Please Select Type',
    OPTION_EMP_TYPE: 'Please Select Employee Type',
    CCC_EXAM_MANDATORY: 'CCC/CCC+ exams are mandatory',

    // Employee Creation
    SALUTATION: 'Please select Option',
    EMPLOYEE_NAME: 'Please Enter Employee Name',
    GENDER: 'Please select Gender',
    NATIONALITY: 'Please select Nationality',
    EMPLOYEE_MOBILENO: 'Please Enter Employee Mobile No.',
    EMPLOYEE_EMAIL: 'Please Enter Email ID',
    FATHERS_NAME: 'Please Enter Employee Father Name',
    MOTHER_NAME: 'Please Enter Employee Mother Name',
    MARITAL_STATUS: 'Please Select Employee Marital Status',
    CATEGORY: 'Please select Category',
    RELIGION: 'Please Enter Religion',
    CASTE: 'Please Enter Caste',
    PH_STATUS: 'Please select Divyang (PH) Status',
    PH_TYPE: 'Please select PH Type',
    IDENTIFICATION_MARK: 'Please Enter Identification Mark',
    HEIGHT: 'Please Enter Height',
    PAN_NO: 'Please Enter Permanent Account No.(PAN)',
    STATE: 'Please select State',
    DISTRICT: 'Please select District',
    TALUKA: 'Please select Taluka',
    CITY_VILLAGE: 'Please Enter City/ Village',
    PIN_CODE: 'Please Enter Pincode',
    OFFICE_DISTANCE: 'Please select Distance from Office',
    EMP_CATEGORY: 'Please select Employee Type',
    EMP_STATUS: 'Please select Type of Employement',
    EMP_TYPE: 'Please select Employee PayType',
    PARENT_ADMIN_DEPT: 'Please select Parent Administrative Department',
    HEAD_OF_DEPT: 'Please select Head of Department',
    EMP_CLASS: 'Please select Employee Class',
    DEPARTMENTAL_CATEGORY: 'Please select Departmental Category',
    STATION: 'Please Enter Station',
    DEPT_NAME: 'Please Enter Department Name',
    OFFICE_ADD: 'Please Enter Office Address',
    EMP_DESIGNATION_HIST: 'Please select Employee Designation',
    LAST_PAY_DRAWN: 'Please Enter Last Pay Drawn',
    IS_SERVICE_CONTINUE: 'Please select Option',
    ORDER_NO_DATE: 'Please Enter Order No & Date',

    // Error Messages for Suspension
    REASON_FOR_SUSPENSION: 'Please select Reason for Suspension',
    SUSPENSION_START_DATE: 'Please select Suspension Start Date',
    SUSPENSION_END_DATE: 'Please select Suspension End Date',
    SUSPENSION_CLOSURE_DATE: 'Please select Suspension Closure Date',
    DESCRIPTION: 'Please fill Description',
    CLOSURE: 'Please select Closure',
    TYPE_OF_PUNISHMENT: 'Please fill Type of Punishment',
    SUSPENSION_EFFECTIVE_DATE: 'Please select Suspension Effective Date',
    SUSPENSION_EVENT_DATE: 'Please select Suspension Event Date',
    SUSPENSION_ORDER_NO: 'Please fill Supension Order Number',
    SUSPENSION_ORDER_DATE: 'Please select Suspension Order Date',

    // Error Messages for Selection Grade CAS
    CAS_Type: 'Please select Career Advancement Scheme Type',
    UNIVERSITY_APPROVED_LECTURER: 'Please fill University Approved Lecturer',
    ORIENTATION_COURSE: 'Please select Orientation Course Attended',
    ORIENTATION_DATE: 'Please select Orientation Date',
    REFRESHER_COURSE: 'Please select Refresher Course Attended',
    REFRESHER_DATE: 'Please select Refresher Course Date',

    // STEPPING UP ERROR MESSAGES
    JUNIOR_EMP_NO: 'Please Enter Employee Number',
    EVENT_DATE: 'Please Select Event Order Date',
    EVENT_ORD_NUMBER: 'Please Enter Event Order Number',

    // EOL ERROR MESSAGES
    LEAVE_START: 'Please Select Leave Start Date',
    LEAVE_END: 'Please Select Leave End Date',
    SUB_TYPE: 'Please Select Leave End Date',

    CARDEX_NO: 'Please Select Cardex Number',
    DDO_NO: 'Please Select DDO Number',
    FORENOON_AFTERNOON: 'Please Select Forenoon/ Afternoon',
    DECLINED_PROMOTION: 'Please Select Option',

    DESIGNATION_TXT: 'Please Enter Designation',

    // Assures Career Progression ERROR MESSAGES
    ACP_TYPE: 'Please Select Type',
    REG_PROMOTION: 'Please select declined regular promotion on any personal ground',
    WORKFLOW: {
        CLOSE: 'Do you want to Processed ?',
        WF_USER_LIST_EMPTY: 'Workflow user not mapped!',
        VALIDATION: {
            TOASTR: 'Please fill all the details',
            TOASTR_NOMINEE: 'Please fill nominee details',
            TOASTR_REQUIRED: 'Please fill required details',
            TOASTR_SAVE: 'Data saved successfully',
            OTHER_REASON: 'Please Enter Other Reason',
            TOASTR_UPDATE: 'Data updated successfully'
        }
    }
};

export const EVENT_APIS = {
    EMPLOYEE_DETAILS: 'pvu/get-regular-common-detail',
    EMPLOYEE_DETAILS_SHETTY_PAY: 'pvu/sp/get-regular-common-detail',
    EMPLOYEE_EXAM_DETAILS: 'pvu/get-employee-exams',
    PVU_EVENTS: 'pvu/pvu-events',
    GET: '301',
    CREATE: '101',
    UPDATE: '401',
    DESIGNATIONS: 'masters/designations/201',
    // DESIGNATIONS: 'pvu/designations',
    PAY_MASTERS: 'pvu/pay-masters',
    PAY_COMM: 'pvu/paycommision',
    PRINT_COMPARISON_STATEMENT: 'pvu/event/steppingup/generate-comparision-report/101',
    OPTION_CALCULATE_API: 'pvu/option/calculate/601',
    HIGHER_PAY_SCALE_APIs: {
        CHECK_ELIGIBILITY: 'pvu/employehigherpayscaleevent/eligible/higher/pay',
        CHECK_FOR_DATE_NXT_INCR: 'pvu/check-employee-eligible',
        CAL_SEVEN_BASIC: 'pvu/seven/basic/pay',
        CAL_SIX_BASIC: 'pvu/six/basic/pay'
    },
    Assured_Career_Progression: {
        SIXTH_PAY_MASTERS: 'pvu/assured-career-progression/sixthPayScalVal/301',
        CHECK_ELIGIBILITY: 'pvu/assured-career-progression/employeedetail/301'
    },
    CAREER_ADVANCEMENT_SCHEME: {
        CURRENT_DETAILS: 'pvu/careeradvancevent/getCurtDetail',
        CHECK_FOR_DATE_NXT_INCR: 'pvu/check-employee-eligible',
        CAL_SEVEN_BASIC: 'pvu/seven/basic/pay',
        CAL_SIX_BASIC: 'pvu/six/basic/pay'
    },
    TIKU_PAY_APIs: {
        CHECK_ELIGIBILITY: 'pvu/tikupay/getEmployeeCurrentDetail',
        CHECK_FOR_DATE_NXT_INCR: 'pvu/check-employee-eligible',
        CAL_SEVEN_BASIC: 'pvu/seven/basic/pay',
        CAL_SIX_BASIC: 'pvu/six/basic/pay'
    },
    SELECTION_GRADE_APIs: {
        CAL_SEVEN_BASIC: 'pvu/selectiongrade/seven/basic/cell'
    },
    LIST: {
        GET_LOOKUP_DATA: 'pvu/get-all-lookup',
        LIST_DATA: {
            Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/ddo-wf-listing',
            Tiku_Pay: 'pvu/tikupay/tikupay-ddo-list',
            Assured_Career_Progression: 'pvu/assured-career-progression/acp-ddo-list',
            Stepping_Up: 'pvu/event/steppingup/ddo-wf-listing',
            Selection_Grade: 'pvu/selectiongrade/ddo-wf-listing',
            Shetty_Pay: 'pvu/employeshettypay/speventsearch/201',
            Career_Advancement_Scheme: 'pvu/careeradvancevent/ddo-wf-listing',
            Senior_Scale_PVU: 'pvu/senior-scale/ddo-wf-listing',
            Change_of_Scale_PVU: 'pvu/csevent/common-details-cspvu-ddo',
        },
        WORKFLOW_STATUS: 'pvu/pvu-event-wf-status'
    },
    DELETE_TRANSACTION: {
        Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/501',
        Tiku_Pay: 'pvu/tikupay/501',
        Assured_Career_Progression: 'pvu/assured-career-progression/501',
        Stepping_Up: 'pvu/event/steppingup/501',
        Selection_Grade: 'pvu/selectiongrade/501',
        Shetty_Pay: 'pvu/employeshettypay/501',
        Career_Advancement_Scheme: 'pvu/careeradvancevent/501',
        Senior_Scale_PVU: 'pvu/senior-scale/501',
        Change_of_Scale_PVU: 'pvu/csevent/501'
    },
    ATTACHMENT_PREFIX: {
        Higher_Pay_Scale: 'pvu/employehigherpayscaleevent',
        Tiku_Pay: 'pvu/tikupay',
        Assured_Career_Progression: 'pvu/assured-career-progression',
        Stepping_Up: 'pvu/event/steppingup',
        Selection_Grade: 'pvu/selectiongrade',
        Shetty_Pay: 'pvu/employeshettypay',
        Career_Advancement_Scheme: 'pvu/careeradvancevent',
        Senior_Scale_PVU: 'pvu/senior-scale',
        Change_of_Scale_PVU: 'pvu/csevent',
    },
    CRUD: {
        Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/',
        Tiku_Pay: 'pvu/tikupay/',
        Assured_Career_Progression: 'pvu/assured-career-progression/',
        Stepping_Up: 'pvu/event/steppingup/',
        Selection_Grade: 'pvu/selectiongrade/',
        Shetty_Pay: 'pvu/employeshettypay/',
        Career_Advancement_Scheme: 'pvu/careeradvancevent/',
        Senior_Scale_PVU: 'pvu/senior-scale/',
        Change_of_Scale_PVU: 'pvu/csevent/',
    },
    LOOK_UP: {
        Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/get-all-lookup',
        Tiku_Pay: 'pvu/tikupay/tikupay_lookup',
        Assured_Career_Progression: 'pvu/assured-career-progression/get-all-lookup',
        Stepping_Up: 'pvu/event/steppingup/create_lookup',
        Senior_Scale_PVU: 'senior-scale/',
        Change_of_Scale_PVU: 'pvu/csevent/pvu/getAllLookup',
        Shetty_Pay: '',
        Career_Advancement_Scheme: 'pvu/careeradvancevent/getAllLookup'
    },
    SHETTY_PAY_API: {
        CHECK_ELG_SP: 'pvu/employeshettypay/check-emp-eligible-sp',
    },
    STEPPING_UP_API: {
        VALIDATE_EMPLOYEE: 'pvu/event/steppingup/chkCondition',
    },
    PVU_WORKFLOW: {
        INWARD: {
            INWARD_LOOKUP: 'pvu/pvu-inward/lookup/201',
            GET_INWARDS: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/higherpay-inward/201',
                Tiku_Pay: 'pvu/tikupay/tikupay-inward/201',
                Assured_Career_Progression: 'pvu/assured-career-progression/acp-inward/201',
                Stepping_Up: 'pvu/event/steppingup/steppingup-inward/201',
                Selection_Grade: 'pvu/selectiongrade/selection-inward/201',
                Shetty_Pay: 'pvu/employeshettypay/inward-list/501',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/careerAdvance-inward/201',
                Senior_Scale_PVU: 'pvu/senior-scale/ssp-inward/201',
                Change_of_Scale_PVU: 'pvu/csevent/csp-inward/201'
            },
            RECEIVE: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/receive-inward',
                Tiku_Pay: 'pvu/tikupay/receive-inward',
                Assured_Career_Progression: 'pvu/assured-career-progression/receive-inward',
                Stepping_Up: 'pvu/event/steppingup/receive-inward',
                Selection_Grade: 'pvu/selectiongrade/receive-inward',
                Shetty_Pay: 'pvu/employeshettypay/receive-inward',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/generateInwardNumber/201',
                Senior_Scale_PVU: 'pvu/senior-scale/receive-inward',
                Change_of_Scale_PVU: 'pvu/csevent/receive-inward'
            },
            SUBMIT: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/submit-inward',
                Tiku_Pay: 'pvu/tikupay/submit-inward',
                Assured_Career_Progression: 'pvu/assured-career-progression/submit-inward',
                Stepping_Up: 'pvu/event/steppingup/submit-inward',
                Selection_Grade: 'pvu/selectiongrade/submit-inward',
                Shetty_Pay: 'pvu/employeshettypay/submit-inward',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/inwardSubmit/901',
                Senior_Scale_PVU: 'pvu/senior-scale/submit-inward',
                Change_of_Scale_PVU: 'pvu/csevent/submit-inward'
            }
        },
        LIST: {
            WORKFLOW_STATUS: 'common/workflow/getWfStatus/201'
        },
        DISTRIBUTOR: {
            SUBMIT: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/distributorSubmit/901',
                Tiku_Pay: 'pvu/tikupay/distributorSubmit/901',
                Assured_Career_Progression: 'pvu/assured-career-progression/distributorSubmit/901',
                Stepping_Up: 'pvu/event/steppingup/distributorSubmit/901',
                Selection_Grade: 'pvu/selectiongrade/distributorSubmit/901',
                Shetty_Pay: 'pvu/employeshettypay/distributorSubmit/901',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/distributorSubmit/901',
                Senior_Scale_PVU: 'pvu/senior-scale/submit-distributor',
                Change_of_Scale_PVU: 'pvu/csevent/distributorSubmit/901'
            }
        },
        AUDITOR_VERIFIER_APPROVER: {
            REASONS_LIST: 'pvu/senior-scale/reasons',
            LOOK_UP: 'pvu/aud-ver-app/look-up',
            TRNS_WF_CODE: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/wfrolecode/201',
                Tiku_Pay: 'pvu/tikupay/wfrolecode/tikupay/201',
                Assured_Career_Progression: 'pvu/assured-career-progression/wfrolecode/acp/201',
                Stepping_Up: 'pvu/event/steppingup/wfrolecode/steepingup/201',
                Selection_Grade: 'pvu/selectiongrade/wfrolecode/201',
                Shetty_Pay: 'pvu/employeshettypay/wfrolecode/201',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/wfrolecode/201',
                Senior_Scale_PVU: 'pvu/senior-scale/wfrolecode/ssp/201',
                Change_of_Scale_PVU: 'pvu/csevent/wfrolecode/csp/201'
            },
            UPDATE_REMARKS: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/update-remarks',
                Tiku_Pay: 'pvu/tikupay/pvuInsertUpdateRemark/401',
                Assured_Career_Progression: 'pvu/assured-career-progression/acpremark/401',
                Stepping_Up: 'pvu/event/steppingup/pvuInsertUpdateRemark/401',
                Selection_Grade: 'pvu/selectiongrade/spremark/401',
                Shetty_Pay: 'pvu/employeshettypay/spremark/401',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/update-remarks',
                Senior_Scale_PVU: 'pvu/senior-scale/update-remarks',
                Change_of_Scale_PVU: 'pvu/csevent/update-remarks'
            },
            SAVED_RETURN_REMARKS: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/return-remarks',
                Tiku_Pay: 'pvu/tikupay/return-remarks',
                Assured_Career_Progression: 'pvu/assured-career-progression/remarks',
                Stepping_Up: 'pvu/event/steppingup/return-remarks',
                Selection_Grade: 'pvu/selectiongrade/return-remarks',
                Shetty_Pay: 'pvu/employeshettypay/remarks',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/return-remarks',
                Senior_Scale_PVU: 'pvu/senior-scale/return-remarks',
                Change_of_Scale_PVU: 'pvu/csevent/return-remarks'
            },
            GET_DATA: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/pvu-response',
                Tiku_Pay: 'pvu/tikupay/pvu-response',
                Assured_Career_Progression: 'pvu/assured-career-progression/pvu-response',
                Stepping_Up: 'pvu/event/steppingup/pvu-response',
                Selection_Grade: 'pvu/selectiongrade/pvu-response',
                Shetty_Pay: 'pvu/employeshettypay/pvu-response',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/pvu-response',
                Senior_Scale_PVU: 'pvu/senior-scale/pvu-response',
                Change_of_Scale_PVU: 'pvu/csevent/pvu-response'
            },
            GET_LIST_DATA: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/employeesearch/901',
                Tiku_Pay: 'pvu/tikupay/employeesearch/901',
                Assured_Career_Progression: 'pvu/assured-career-progression/employeesearch/901',
                Stepping_Up: 'pvu/event/steppingup/employeesearch/901',
                Selection_Grade: 'pvu/selectiongrade/employeesearch/901',
                Shetty_Pay: 'pvu/employeshettypay/auditor-list/501',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/employeesearch/901',
                Senior_Scale_PVU: 'pvu/senior-scale/employeesearch/901',
                Change_of_Scale_PVU: 'pvu/csevent/employeesearch/901'
            },
            OFFICE_LIST: 'edp/msoffice/officebyofficeidandpvuid/301'
        },
        PRINT_ORDER: {
            LOOKUP: 'pvu/pvu-inward/lookup/201',
            ROLLBACK_PRINT_COUNT: 'pvu/rollback-reprint',
            GET_LIST: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/hps-endorsement-list',
                Tiku_Pay: 'pvu/tikupay/print-endorsement-list',
                Assured_Career_Progression: 'pvu/assured-career-progression/print-endorsement-list',
                Stepping_Up: 'pvu/event/steppingup/steppingup-printendorsement/201',
                Selection_Grade: 'pvu/selectiongrade/print-endorsement-list',
                Shetty_Pay: 'pvu/employeshettypay/print-endorsement-list',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/cas-print-endorsement-list',
                Senior_Scale_PVU: 'pvu/senior-scale/ssp-print-endorsement-list',
                Change_of_Scale_PVU: 'pvu/csevent/print-endorsement-list'
            },
            MULTIPLE_ORDER: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/generate-printendorsement/201',
                Tiku_Pay: 'pvu/tikupay/generate-printendorsement/201',
                Assured_Career_Progression: 'pvu/assured-career-progression/generate-printendorsement/201',
                Stepping_Up: 'pvu/event/steppingup/generate-printendorsement/201',
                Selection_Grade: 'pvu/selectiongrade/generate-printendorsement/201',
                Shetty_Pay: 'pvu/employeshettypay/generate-printendorsement/201',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/generate-printendorsement/201',
                Senior_Scale_PVU: 'pvu/senior-scale/generate-print-orders',
                Change_of_Scale_PVU: 'pvu/csevent/generate-printendorsement/201'
            },
            SINGLE_ORDER: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/generate-printendorsement/101',
                Tiku_Pay: 'pvu/tikupay/generate-printendorsement/101',
                Assured_Career_Progression: 'pvu/assured-career-progression/generate-printendorsement/101',
                Stepping_Up: 'pvu/event/steppingup/generate-printendorsement/101',
                Selection_Grade: 'pvu/selectiongrade/generate-printendorsement/101',
                Shetty_Pay: 'pvu/employeshettypay/generateprintendorsement/101',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/generate-printendorsement/101',
                Senior_Scale_PVU: 'pvu/senior-scale/generate-print-order',
                Change_of_Scale_PVU: 'pvu/csevent/generate-printendorsement/101'
            },
            REPRINT_REMARKS_HISTORY: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/endorsementremarks/101',
                Tiku_Pay: 'pvu/tikupay/endorsementremarks/101',
                Assured_Career_Progression: 'pvu/assured-career-progression/endorsementremarks/101',
                Stepping_Up: 'pvu/event/steppingup/endorsementremarks/101',
                Selection_Grade: 'pvu/selectiongrade/endorsementremarks/101',
                Shetty_Pay: 'pvu/employeshettypay/endorsementremarks/101',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/endorsementremarks/101',
                Senior_Scale_PVU: 'pvu/senior-scale/endorsementremarks/101',
                Change_of_Scale_PVU: 'pvu/csevent/endorsementremarks/101'
            }
        },
        OUTWARD: {
            LOOKUP: 'pvu/pvu-outward/lookup/201',
            GET_OUTWARDS: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/hps-outward-list/201',
                Tiku_Pay: 'pvu/tikupay/pvu-outward/201',
                Assured_Career_Progression: 'pvu/assured-career-progression/csp-outward/201',
                Stepping_Up: 'pvu/event/steppingup/steppingup-outward/201',
                Selection_Grade: 'pvu/selectiongrade/sg-outward/201',
                Shetty_Pay: 'pvu/employeshettypay/csp-outward/201',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/careerAdvance-outward-list/201',
                Senior_Scale_PVU: 'pvu/senior-scale/ssp-outward/201',
                Change_of_Scale_PVU: 'pvu/csevent/csp-outward/201'
            },
            RECEIVE: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/receive-outward',
                Tiku_Pay: 'pvu/tikupay/receive-outward',
                Assured_Career_Progression: 'pvu/assured-career-progression/receive-outward',
                Stepping_Up: 'pvu/event/steppingup/receive-outward',
                Selection_Grade: 'pvu/selectiongrade/receive-outward',
                Shetty_Pay: 'pvu/employeshettypay/receive-outward',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/receive-outward',
                Senior_Scale_PVU: 'pvu/senior-scale/receive-outward',
                Change_of_Scale_PVU: 'pvu/csevent/receive-outward'
            },
            SUBMIT: {
                Higher_Pay_Scale: 'pvu/employehigherpayscaleevent/submit-outward',
                Tiku_Pay: 'pvu/tikupay/submit-outward',
                Assured_Career_Progression: 'pvu/assured-career-progression/submit-outward',
                Stepping_Up: 'pvu/event/steppingup/submit-outward',
                Selection_Grade: 'pvu/selectiongrade/submit-outward',
                Shetty_Pay: 'pvu/employeshettypay/submit-outward',
                Career_Advancement_Scheme: 'pvu/careeradvancevent/submit-outward',
                Senior_Scale_PVU: 'pvu/senior-scale/submit-outward',
                Change_of_Scale_PVU: 'pvu/csevent/submit-outward'
            }
        }
    }
};

export const currentEmployeeDetailsIfNotAvailable = {
    linkMenuId: 49,
    lkPoOffUserId: 486,
    menuId: 49,
    officeDetail: {
        activeStatus: 1,
        addrLine1: 'Block-D, ground floor. M S Building, Sector-1',
        addrLine2: '',
        addressDescription: '',
        addressDescriptionGuj: '',
        billStatus: null,
        billSubmittedTo: null,
        billType: null,
        billTypeSelected: null,
        cardexno: 1,
        coDesgName: null,
        coId: null,
        coOfficeName: null,
        comment: null,
        createdBy: 0,
        createdByPost: 0,
        createdDate: '2008-10-17T10:44:06.000+0530',
        ddoNo: '416',
        ddoType: 68,
        ddoTypeName: null,
        departmentId: 17,
        deptName: 'Finance Department',
        desgDdoId: 811,
        desgDdoName: null,
        digitalSigEnable: 2,
        distName: 'Gandhinagar',
        districtId: 25,
        districtName: 'Gandhinagar',
        emailId: '',
        employeeName: '',
        employeeNo: '',
        faxNo: '',
        formAction: null,
        grNo: '',
        grantRcvngCardex: 1,
        hodId: 38,
        hodName: null,
        isCo: 1,
        isCoName: null,
        isFd: 1,
        isHod: 1,
        isNewOffice: null,
        isSubTreasury: 1,
        isTreasury: 2,
        isUpdate: null,
        isVerified: 2,
        levelId: null,
        levelName: null,
        menuShName: null,
        mobileNo: '',
        moduleId: null,
        msgFlag: null,
        nonDdo: null,
        nonDdoTypeName: null,
        objRemark: null,
        objStatus: null,
        offStComments: null,
        officeCode: '10109',
        officeCodeGuj: '',
        officeCodeName: '',
        officeDivision: null,
        officeEndDate: null,
        officeId: 993,
        officeName: 'District Treasury Office, Gandhinagar',
        officeNameAlias: null,
        officeNameDisp: 'District Treasury Office, Gandhinagar',
        officeNameGuj: '',
        officePVU: null,
        officeRangeId: null,
        officeShortName: 'GNR',
        officeShortNameGuj: '',
        officeStatus: 283,
        officeType: null,
        officeTypeId: 71,
        officeTypeName: 'Drawing and Disbursing office (DDO)',
        parentOfficeId: 38,
        phoneNo: '',
        pincode: '',
        prvOfficeStatus: null,
        prvOfficeStatusId: null,
        pvuId: 38,
        pvuName: null,
        requestNo: null,
        requestTo: null,
        requestToName: null,
        selectedBills: null,
        station: '',
        statusId: 327,
        stdCode: null,
        talukaId: null,
        talukaName: null,
        transactionNo: '20-21/EDP/CNO/00993',
        treasuryType: null,
        treasuryTypeName: null,
        uniqueId: '57/416/1/00',
        updateOffice: null,
        updatedBy: 0,
        updatedByPost: 0,
        updatedDate: '2020-03-02T18:11:17.804+0530',
        verifiedDate: '2010-06-10T12:07:07.000+0530',
        wfRoleId: null,
        workFlowId: null
    },
    postId: 204,
    userId: '9vo/sJUOHEQ=',
    wfRoleId: [1]
};
