export const MessageConst = {
    VALIDATION: {
        TOASTR: 'Please fill all the details',
        TOASTR_NOMINEE: 'Please fill nominee details',
        TOASTR_REQUIRED: 'Please fill required details',
        TOASTR_SAVE: 'Data saved successfully',
        TOASTR_UPDATE: 'Data updated successfully',
        ACCOUNT_NOT_MATCH: 'Account Number should be Match'
    },
    ERRORMESSAGE: {

    }
};

export const commonMessage = {
};


export const pvuMessage = {
    SELECT_VALID_DATE: 'Please Select Valid Date',
    WF_USER_LIST_EMPTY: 'Workflow user not mapped!',
    NOM_PER_ERR: 'Total of Nominee Share should not be greater than 100%',
    UPLOAD_NPS_NOM_FORM_TYPE_ERR: 'Please select valid NPS Nomination Form!',
    UPLOAD_NOM_DECL_FORM_TYPE_ERR: 'Please select valid Nominee Declared Form!',
    UPLOAD_NOM_PHOTO_TYPE_ERR: 'Please select valid Nominee Photo!',
    UPLOAD_PHOTO_TYPE_ERR: 'Please select valid Employee Photo!',
    UPLOAD_PHOTO_SIZE_ERR: 'Please upload less than 1 MB file!',
    EMPL_PHOTO_SIZE_ERR: 'Please upload less than 300 KB file!',
    IS_APPLICABLE_UNCHECK_MSG: 'Are you sure you want to remove Previous Employement History?',
    CLOSE: 'Do you want to proceed ?',
    RESET: 'Do you want to proceed ?',
    DELETE: 'Are you sure you want to Delete this Record?',
    DELETE_ATTACHMENT: 'Are you sure you want to Delete this Attachment?',
    DELETE_EMPLOYEE_PHOTO: 'Are you sure you want to Delete this Employee Photo?',
    EVENT: 'Please select Event',
    PAY_COMMISSION: 'Please select Applicable Pay Commission(Joining Time)',
    INCREMENT_TYPE: 'Please select Incremnet Type',
    ORDER_NO: 'Please Enter Order Number',
    ORDER_DATE: 'Please Enter Order Date',
    PAY_BAND: 'Please Select Pay Band',
    GRADE_PAY: 'Please Select Grade Pay',
    PAY_LEVEL: 'Please Select Pay Level',
    PAY_SCALE: 'Please Select Pay Scale',
    IFSC_CODE: 'Please Select IFSC Code',
    ENTER_PAY_SCALE: 'Please Enter Pay Scale',
    BANK_ACC_NO: 'Please Enter Account Number',
    ACC_NO_NOT_MATCH: 'Entered Account Number is not match',
    VALID_BANK_ACC_NO: 'Please Enter Valid Account Number',
    ACCOUNT_TYPE: 'Please Select Account Type',
    BASIC_PAY_FORTH_FIFTH: 'Please Enter Basic Pay',
    CELL_ID: 'Please Select Cell ID',
    INCREMENT_AMT: 'Please Select Option',
    OPTION_AVAILED: 'Please Select Option availed or Not',
    OPTION_TYPE: 'Please Select Type',
    BENEFIT_EFFECTIVE_DATE: 'Please select Benefit Effective Date',
    DATE_OF_NEXT_INCREMENT: 'Please Select Date of Next Increment',
    EVENT_ORDER_DATE: 'Please Select Event Order Date',
    CLASS: 'Please Select Class',
    DESIGNATION: 'Please Select Designation',
    PAY_BAND_VALUE: 'Please Select Pay Band Value',
    BASIC_PAY: 'Please Select Basic Pay',
    EVENT_ORDER_NUMBER: 'Please Select Event Order Number',
    DATE_OF_JOINING: 'Please Select Date of Joining',
    DATE_OF_RETIREMENT: 'Please select Date of Retirement',
    EVENT_EFFECTIVE_DATE: 'Please Select Event Effective Date',
    OFFICE_NAME: 'Please Enter Office Name',
    OPTION_DATE: 'Please Select Option date',
    NOMINEE_SHARE_GREATER: 'Nominee share should not be greater then 100 %.',
    NOMINEE_SHARE_LESS: 'Nominee share should not be less then 100 %.',
    NOMINEE_ATTACH: 'Please upload the Nominee Declared Form!',

    // Promotion Forgo
    PROMOTION_FOR: 'Please Select Promotion Porgo For',
    PROMOTION_DATE: ' Please Select Promotion Date',
    PROMOTION_FORGO_DATE: 'Please Select Promotion Forgo Date',
    HIGHER_GRADE: 'Please Select Higher Grade',

    // Increment
    FINANCIAL_YEAR: 'Please Select Financial Year',
    INCREMENT_FOR: 'Please Select Increment For',
    EMPLOYEE_TYPE: 'Please Select Employee Type',
    EFFECTIVE_DATE_MSG_7PAY: 'Increment effective date must be 01/01 or 01/07',
    EFFECTIVE_DATE_MSG_6PAY: 'Increment effective date must be 01/07',
    EFFECTIVE_DATE_MSG_5PAY: 'Increment effective date is not proper',
    ERR_BASIC_PAY: 'Please enter valid basic pay',
    CPF_GPF_PPAN_MAX: 'CPF/GPF/PPAN No. should not allow more then 20 Characters',
    EMP_NO_MAX: 'Employee number should be of 10 digits!',
    EXCLUSION_REASON: 'Please Select Reason for exclusion',
    REASON_FOR_STOP: 'Please select Stop increment',
    INCREMENT_EFFECTIVE_DATE: 'Please Select Increment Effective Date',

    // REVISED_BASIC_PAY
    REVISED_BASIC_PAY: 'Please Select Revised Basic Pay',
    REVISED_BASIC_PAY_VALUE: 'Please Select Revised Basic Pay Value',

    // Tikypay
    TIKU_PAY_TYPE: 'Please Select Tiku Pay Type',
    ADHOC: 'Please Select Adhoc',
    FROM_DATE: 'Please Select From Date',
    TO_DATE: 'Please Select To Date',
    ADHOC_CONTINIOUS_SERVICES: 'Please Select Adhoc Continious Services',
    GPSC_EXAM_PASSED: 'Please Select Gpsc Exam Passed',
    GPSC_EXAM_PASSED_DATE: 'Please Select Gpsc Exam Passed Date',
    EMP_NO: 'Please fill Employee Number',
    TYPE: 'Please Select Option',

    // Transfer

    // Higher Pay Scale
    HIGHER_PAY_TYPE: 'Please Select Type',
    OPTION_EMP_TYPE: 'Please Select Employee Type',

    // Employee Creation
    SALUTATION: 'Please select Salutation',
    EMPLOYEE_NAME: 'Please Enter Employee Name',
    EMPLOYEE_SURNAME: 'Please Enter Surname',
    GENDER: 'Please select Gender',
    NATIONALITY: 'Please select Nationality',
    EMPLOYEE_MOBILENO: 'Please Enter Employee Mobile No.',
    EMPLOYEE_EMAIL: 'Please Enter Email ID',
    DATE_OF_BIRTH: 'Please select Date of Birth',
    FATHERS_NAME: 'Please Enter Employee Father Name',
    MOTHER_NAME: 'Please Enter Employee Mother Name',
    MARITAL_STATUS: 'Please Select Employee Marital Status',
    PHSTATUS: 'Please select PH Status',
    CATEGORY: 'Please select Category',
    RELIGION: 'Please Enter Religion',
    CASTE: 'Please Enter Caste',
    PH_STATUS: 'Please select Divyang (PH) Status',
    PH_TYPE: 'Please select PH Type',
    OTHER_PH_CATEGORY: 'Please enter % level of PH',
    IDENTIFICATION_MARK: 'Please Enter Identification Mark',
    HEIGHT: 'Please Enter Height',
    PAN_NO: 'Please Enter Permanent Account No.(PAN)',
    // PAN_NO: 'Please Enter valid 10 digit PAN Number',
    STATE: 'Please select State/UT',
    DISTRICT: 'Please select District',
    TALUKA: 'Please select Taluka',
    CITY_VILLAGE: 'Please Enter City/ Village',
    PIN_CODE: 'Please Enter Pincode',
    OFFICE_DISTANCE: 'Please select Distance from Office',
    EMP_CATEGORY: 'Please select Employee Type',
    EMP_STATUS: 'Please select Type of Employement',
    DEPUTATION_START_DATE: 'Please select Deputation Start Date',
    DEPUTATION_END_DATE: 'Please select Deputation End Date',
    EMP_PAY_TYPE: 'Please select Employee Pay Type',
    PARENT_ADMIN_DEPT: 'Please select Parent Administrative Department',
    HEAD_OF_DEPT: 'Please select Head of Department',
    EMP_CLASS: 'Please select Employee Class',
    DEPARTMENTAL_CATEGORY: 'Please select Departmental Category',
    STATION: 'Please Enter Station',
    DEPT_NAME: 'Please Enter Department Name',
    OFFICE_ADD: 'Please Enter Office Address',
    EMP_DESIGNATION_HIST: 'Please select Employee Designation',
    LAST_PAY_DRAWN: 'Please Enter Last Pay Drawn',
    IS_SERVICE_CONTINUE: 'Please select Option',
    ORDER_NO_DATE: 'Please Enter Order No & Date',
    EMP_TYPE: 'Please select Employee Type',
    EMPLOYEMENT_TYPE: 'Please select Employement Type',
    DESIGNATION_AS_ON: 'Please select designation',
    PREREVISED_PAYSCALE: 'Please select pre-revised pay scale.',
    PREREVISED_BASICPAY: 'Please enter pre-revised basic pay.',
    REVISED_PAYBAND: 'Please select revised pay band.',
    PAYBAND_6PAY: 'Please enter six pay band value.',
    GRAD_PAY: 'Please select grad pay value.',
    NPA: 'Please select NPA',
    OPTN_DATE: 'Please select option Date',
    PASSPORT_DATE: 'Please select passport expiry date',
    BASIC_NOT_CALCULATED: 'Unabled to fetch Basic Pay based on.',
    OTHER_RELATION: 'Please enter Other Relationship Name.',
    DUPLICATE_PAN: 'PAN is already exist.',
    AGE_ERROR: 'Age should be greater than or equal to 18 years.',
    BASIC_PAY_RANGE: 'Please enter valid basic pay between payscale range',
    BASIC_PAY_BAND_RANGE: 'Please enter basic pay between pay band range',

    ADDRESS_1: 'Please Enter Address Detail',
    N_STATE: 'Please select any State',
    N_DISTRICT: 'Please select any District',
    N_TALUKA: 'Please select any Taluka',
    N_CITY_VILLAGE: 'Please Enter City/ Village',
    C_CITY_VILLAGE: 'Please Enter City/ Village',
    P_CITY_VILLAGE: 'Please Enter City/ Village',
    N_PIN_CODE: 'Please Enter Pincode',
    P_STATE: 'Please select any State',
    P_DISTRICT: 'Please select District',
    P_PIN_CODE: 'Please Enter Pincode',
    C_STATE: 'Please select State/UT',
    C_DISTRICT: 'Please select District',
    C_CITY_TALUKA: 'Please select Taluka',
    C_PIN_CODE: 'Please Enter Pincode',
    C_OFFICE_DIST: 'Please select any Option',
    APPLICABLE_PAY_COMM: 'Please select Pay Commission',
    INCREMENT_AMOUNT: 'Please Enter Increment Amount',
    FIX_PAY_VALUE: 'Please enter fix pay value',
    EFFECTIVE_DATE: 'Please select effective date',

    // Error Messages for Suspension
    REASON_FOR_SUSPENSION: 'Please select Reason for Suspension',
    SUSPENSION_START_DATE: 'Please select Suspension Start Date',
    SUSPENSION_END_DATE: 'Please select Suspension End Date',
    SUSPENSION_CLOSURE_DATE: 'Please select Suspension Closure Date',
    DESCRIPTION: 'Please fill Description',
    CLOSURE: 'Please select Closure',
    TYPE_OF_PUNISHMENT: 'Please fill Type of Punishment',
    SUSPENSION_EFFECTIVE_DATE: 'Please select Suspension Effective Date',
    SUSPENSION_EVENT_DATE: 'Please select Suspension Event Date',
    VALID_DATE: 'Please enter valid date',
    REINSTATE: 'Please select Reinstate',

    // Error Messages for Selection Grade CAS
    CAS_Type: 'Please select Career Advancement Scheme Type',
    UNIVERSITY_APPROVED_LECTURER: 'Please select University Approved Lecturer',
    ORIENTATION_COURSE: 'Please select Orientation Course Attended',
    ORIENTATION_DATE: 'Please select Orientation Date',
    REFRESHER_COURSE: 'Please select Refresher Course Attended',
    REFRESHER_DATE: 'Please select Refresher Course Date',

    // STEPPING UP ERROR MESSAGES
    JUNIOR_EMP_NO: 'Please Enter Employee Number',
    EVENT_DATE: 'Please Select Event Order Date',
    EVENT_ORD_NUMBER: 'Please Enter Event Order Number',


    // EOL ERROR MESSAGES
    LEAVE_START: 'Please Select Leave Start Date',
    LEAVE_END: 'Please Select Leave End Date',
    REMARKS: 'Please fill Remarks',
    CARDEX_NO: 'Please Select Cardex Number',
    DDO_NO: 'Please Select DDO Number',
    DESIGNATION_TXT: 'Please Enter Designation',

    CONFIRMATION_DIALOG: {
        DELETE: 'Are you sure Do you want Delete Record?',
        CONFIRMATION: 'Do you want to Processed?',
        RESET_PASSWORD: 'Are you sure, Do you want Reset Password?'
    },

    INCREMENT_LIST: {
        DATE: 'To Date can not before From Date',
        ERR_Add_DESIGNATION_LIST: 'Some error occurred while fetching Add Designation List!',
        DATA_DELETE: 'Increment record delete successFully',
        ERR_Add_DESIGNATION_DELETE: 'Post record not deleted!',
        FROM_DATE: 'Please Select From Date',
        TO_DATE: 'Please Select To Date'
    },

    // ROP Messages
    ROP_TYPE: 'Please Select ROP Type',
    EFF_DATE: 'Please Select Event Effective Date',
    EMPL_NO: 'Please Enter Employee Number',
    VALID_EMPL_NO: 'Please Enter Valid Employee Number',
    ROP_ORDER_NO: 'Please Enter Order Number',
    ROP_ORDER_DATE: 'Please Select Order Date',
    REASON_FOR_CHANGE: 'Please Select Reason For Change In Effective Date',
    RECOMMENDATION_FOR: 'Please Select Recommendation For',
    ROP_POST_REMARKS: 'Please Enter Remarks',
    ROP_OTHER_REASON: 'Please Enter Other Reason',
    ERR_POST_DETAILS: 'Post Detail are not available',
    ERR_MAND_ATTACHMENT: 'Please Upload Mandatory Attachment',
    ERR_EMP_DETAILS: 'Employee Details are not available',
    ERR_APPROVER_REMARKS: 'Please Enter Approver Remarks',
    RETURN_REASON: 'Please Select Return Reason',

    // Forward dialog messages
    ACTION: 'Please select action',
    USER: 'Please select user',

    // Transfer
    RELIEVE_DATE: 'Please enter Relieving Date',
    REASON: 'Please select Reason for Transfer',
    ACTUAL_DATE: 'Please select Actual Date of Joining',
    NOON_TYPE: 'Please select Forenoon/Afternoon',
    EMP_JOINING: 'Employee Joining Date is ',
    EMP_RETIREMNT: 'Employee Retirement Date is ',

    REMARKS_MAX_Length: 'Maximum Numbers of Characters Allowed is 1000',
    REMARKS_MAX_Length_10000: 'Maximum Numbers of Characters Allowed is 10000',

    DATE_MIN: 'Please enter date greater than ',
    DATE_MAX: 'Please enter date lesser than ',
};


